version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3900:3900"
    networks:
      - ecommerce-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
